version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.8.18-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network