version: '2.4'

services:
  service-discovery:
    image: microservices/service-discovery:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      - SERVER_PORT=8080
      - ZIPKIN_URL=http://zipkin:9411
    networks:
      - microservices_network

  service-drugs:
    image: micmicroservices/drugs:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - ZIPKIN_URL=http://zipkin:9411
      - EUREKA_URL=http://service-discovery:8080/eureka
    networks:
      - microservices_network

  service-recipes:
    image: microservices/recipes:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy
      service-drugs:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - ZIPKIN_URL=http://zipkin:9411
      - EUREKA_URL=http://service-discovery:8080/eureka
      - RABBIT_HOST=rabbitmq
    ports:
      - 18080:8080
    networks:
      - microservices_network

  service-gateway:
    image: microservices/gateway:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      service-discovery:
        condition: service_healthy
      service-drugs:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - ZIPKIN_URL=http://zipkin:9411
      - EUREKA_URL=http://service-discovery:8080/eureka
    ports:
      - 8080:8080
    networks:
      - microservices_network

networks:
  microservices_network:
    name: microservices_network